# This is a basic workflow to help you get started with Actions

name: CI_CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master , Blazor-Support ]
  pull_request:
    branches: [ master , Blazor-Support ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
          
    - name: Build Application
      run: |
        git fetch
        git checkout Blazor-Support
        dotnet build

    - name: Prepare for publish 
      run: |
        git fetch
        git checkout Blazor-Support
        dotnet publish --configuration Release -o dist
        git config --global user.name 'CI_CD Agent'
        git config --global user.email 'skawle631@gmail.com'
        git add -A
        git commit -am "Automated PUBLISH [SUCCESS]"
    
    - name: Copy files from Blazor-Support to master
      run: |
        git fetch
        git checkout Blazor-Support
        git pull
        git checkout master
        git checkout Blazor-Support -- dist/wwwroot
        cp -r dist/wwwroot/* .
        sed '8d' index.html > index.html
    
    - name: Directory Structure 
      run: ls -l
    
    - name: Publish website
      run: |
          git config --global user.name 'CI_CD Agent'
          git config --global user.email 'skawle631@gmail.com'
          git add -A
          git commit -am "Automated DEPLOY [SUCCESS]"
          git push


     
