# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Build Application
      run: dotnet build
    
    - name: Copy wwwroot folder to $GITHUB_REPOSITORY
      run: cp -r wwwroot/* .
    
    - name: LS test
      run: ls -l
    
    - name: Git Add
      run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated report"
          git push


     
