# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ Blazor-Support ]
  pull_request:
    branches: [ master ]
  commit_comment:
    branches: [master,Blazor-Support ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Runner Command
      run: dotnet build
    
    - name: Copy wwwroot folder to home
      run: cp wwwroot .
     
